- name: Run frontend container
  docker_container:
    name: front
    image: stepahnedaniel/myfront:latest
    networks:
      - name: httpnetwork
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python